@startuml
left to right direction
actor "User" <<Human>> as fc

rectangle Service <<Web Service>>{
  usecase "Authentication (Log in or Sign up)" as UC7
}
rectangle Reciclame <<App>> {
  usecase "Locate recycling bins" as UC1
  usecase "Scan items using barcode reader" as UC2
  usecase "Classify products" as UC3
  usecase "Check the news about environment and recycling" as UC4
  usecase "Change the application's language" as UC5
  usecase "Change the user location" as UC6
}



fc --> UC1
fc --> UC2
fc --> UC3
fc --> UC4
fc --> UC5
fc --> UC6

UC1 --> UC7 :<<include>>
UC2 --> UC7 :<<include>>
UC4 --> UC7 :<<include>>
UC5 --> UC7 :<<include>>
UC6 --> UC7 :<<include>>
@enduml